# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('creator', models.CharField(default='', max_length=50)),
                ('num_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
