# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 03:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('time_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_stars', models.IntegerField(default=0)),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('start_lat', models.FloatField(default=0)),
                ('start_lon', models.FloatField(default=0)),
                ('dest_lat', models.FloatField(default=0)),
                ('dest_lon', models.FloatField(default=0)),
                ('description', models.TextField(default='')),
                ('time_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('andrewID', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('schoolyear', models.IntegerField(default=2017)),
                ('home_lat', models.FloatField(default=0)),
                ('home_lon', models.FloatField(default=0)),
                ('avg_rating', models.FloatField(default=0)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='userdata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='attendees',
            field=models.ManyToManyField(related_name='attended_trips', to='backend.UserData'),
        ),
        migrations.AddField(
            model_name='trip',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='backend.UserData'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ratee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='backend.UserData'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='backend.UserData'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='backend.Trip'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.UserData'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='backend.Trip'),
        ),
    ]
